how to init userkeys - getting there 11

diff --git a/tools/myt b/tools/myt
--- a/tools/myt
+++ b/tools/myt
@@ -353,14 +353,18 @@ create_tmux_conf() {
     # echo "Building tmux env using: $profile - saving it in: $conf_file"
     if $t2_env; then
         _s="$(T2_ENV=1 "$profile" -r -t "$TMUX_BIN" "$conf_file")" || {
-            error_msg "Failed to build tmux.conf [$?]"
+            ex_code="$?"
+            log_it "$_s" # failed build
+            error_msg "Failed to build tmux.conf [$ex_code]"
         }
     else
         _s="$("$profile" -r -t "$TMUX_BIN" "$conf_file")" || {
-            error_msg "Failed to build tmux.conf [$?]"
+            ex_code="$?"
+            log_it "$_s" # failed build
+            error_msg "Failed to build tmux.conf [$ex_code]"
         }
     fi
-    log_it "$_s"
+    log_it "$_s" # successful build
 
     log_it # spacer line
 
